README.md, docs/src/index.md, docs/src/reference.md, src/Devito.jl
=> Some work to improve the documentation

.github/workflows/Documentation.yml, .github/workflows/Tests.yml
Updates Documentation.yml and Testing.yml so tests do not fail during installation of mpich
=> Update Documentation.yml and Testing.yml

src/Devito.jl, test/runtests.jl
Also modified associated unit tests.
=> turn subdomain into SubDomain

benchmark/benchmarks.jl, demo/demo_2DAcoIsoDenQ_DEO2.jl, demo/demo_mpi_3DAcoIsoDenQ_DEO2.jl, demo/demo_mpi_azure_3DAcoIsoDenQ_DEO2.jl, docs/src/index.md, src/Devito.jl, test/runtests.jl
Added tuple reversal for grid creation so inputs are julian rather than pythonic
=> Tuple Reversal for Dimensions

src/Devito.jl, test/runtests.jl
where multiplying a function by a scalar in that order used to fail
=> fix for devito multiplication and division 

src/Devito.jl, test/runtests.jl
also modify Dimensions method for compatibility with TimeDimension
=> time_dim for retrieving time dimensions

test/runtests.jl
closes #43 
Note that the tests here will not pass until #41 is merged, and this branch is re-based.  So, before merging we should do the following:
=> add tests for 3D grids

Project.toml, src/Devito.jl, test/runtests.jl
unitary minus operation (-) for devito objects
=> unitary minus

src/Devito.jl, test/runtests.jl
Adding functionality for accessing a grid's stepping dim with
`t = stepping_dim(x::Grid)`
@laughingrice
=> adding stepping_dim(x::Grid) method and tests

src/Devito.jl, test/runtests.jl
and needed equality method for SubDomains to complete the tests
@laughingrice
=> adding interior(x::grid) method, associated unit tests

src/Devito.jl, test/runtests.jl
=> nsimplify method and some tests

src/Devito.jl, test/runtests.jl
also cleaning up arithmetic definitions
=> arithmetic with constants

.gitignore, test/gencodetests.jl, test/runtests.jl
generates code for taking derivatives and checks parity.
=> Test generated code parity between python and Devito.jl 

test/mpitests.jl
Previous tests for `SparseTimeFunction` coordinates with MPI were round trip only, this tests that coords OK in python land.
=> SparseTimeFunction coordinates are set properly with MPI -- add unit test

test/runtests.jl
hopefully this will turn the badge a nicer color. fixes #12
https://app.codecov.io/gh/ChevronETC/Devito.jl/blob/testcov/src/Devito.jl
=> fix code coverage accounting

src/Devito.jl
this should be the last PR needed for the gather/scatter fixes.
=> some janitorial work for the recent MPI gather/scatter changes

src/Devito.jl, test/mpitests_2ranks.jl, test/mpitests_4ranks.jl, test/serialtests.jl
Adding SparseFunction capability and unit tests to Devito.jl
=> Adding SparseFunction to Devito

src/Devito.jl, test/mpitests_2ranks.jl, test/mpitests_4ranks.jl, test/serialtests.jl
coordinates_data returns corresponding array
this results in consistency with the use of the `coordinates` method in devito.py
=> coordinates returns subfunction

src/Devito.jl, test/serialtests.jl
create buffers which can be used as arguments to `save=` in `TimeFunction` construction
=> buffer object support and tests

src/Devito.jl, test/serialtests.jl
ability to make functions and sparsetimefunctions from their corresponding pyobjects
=> making functions from pyobjects

src/Devito.jl, test/csymbolicstests.jl, test/runtests.jl
representing unary ops in c as well as pointers in c
=> adding support for symbolics 

src/Devito.jl, test/serialtests.jl
PyObjects are indeed made from corresponding types
=> ensure Functions and SparseTimeFunctions created from 

Project.toml, src/Devito.jl
so it is compatible with modified _getproperty method of PyCall 1.94.0
=> fix localindicies method 

src/Devito.jl, test/serialtests.jl
also fixing bug with multidimensional SparseFunctions
=> adding support for CoordSlowSparseFunctions

deps/build.jl, src/Devito.jl, test/devitoprotests.jl, test/gencodetests.jl, test/mpitests_2ranks.jl, test/mpitests_4ranks.jl, test/runtests.jl, test/serialtests.jl
modifying Devito.jl so it may optionally be built to include devitopro features
=> include devito pro

.github/workflows/Tests.yml, Project.toml
Remove tests with julia 1.7 which fail with devito
=> Restrict away from Julia 1.7

deps/build.jl, src/Devito.jl, src/utils.py
Nvidia HPC SDK 24.7 and cuda 12.5
=> nvidia hpcx specific updates for devito-pro 

deps/build.jl, src/Devito.jl, src/utils.py, test/devitoprotests.jl
enabled layers=Disk
disabled two broken ABox tests
=> no final mpi4py build

deps/build.jl, test/devitoprotests.jl
Enable use of openmp-gcc and cvxcompress.
=> Support nvidia and openmp-gcc ARCH

.github/workflows/ci.yml, demo/demo_floatx.jl, src/Devito.jl, src/cso.jl, src/utils.py, test/devitoprotests.jl, test/runtests.jl, test/serialtests.jl
Initial PR, mostly familiarizing myself with Devito.jl for the current projects.
Add quantization type to Devito.jl to support Devitopro's Floatx offset/scale quantization for low-precision model parameters.
pro cso for reference (cvx repo):
https://github.com/devitocodespro/devitopro-chevron/blob/main/devitopro/data/cso.py
=> Add support for devitopro FloatX

test/devitoprotests.jl
- add more unit tests for quantized Functions and their data
- add `using PyCall` to devitoprotests for `@pywith` 
- remove all `@test_skip` from devitoprotests
=> added using PyCall for devitoprotests

src/Devito.jl, test/serialtests.jl
=> add support for laplacian and centered derivative shorthand
